onEvent('jei.hide.items', event => {
  event.hide("cyclic:anvil_magma");
  event.hide("cyclic:crystal_chestplate");
  event.hide("cyclic:crystal_boots");
  event.hide("cyclic:crystal_helmet");
  event.hide("cyclic:crystal_leggings");
  event.hide("cyclic:crystal_sword");
  event.hide("cyclic:crystal_pickaxe");
  event.hide("cyclic:crystal_axe");
  event.hide("cyclic:crystal_hoe");
  event.hide("cyclic:crystal_shovel");
  event.hide("cyclic:emerald_boots");
  event.hide("cyclic:emerald_helmet");
  event.hide("cyclic:emerald_chestplate");
  event.hide("cyclic:emerald_leggings");
  event.hide("cyclic:battery");
  event.hide("cyclic:structure");
  event.hide("cyclic:placer");
  event.hide("cyclic:breaker");
  event.hide("cyclic:harvester");
  event.hide("cyclic:charm_home");
  event.hide("cyclic:charm_world");
  event.hide("cyclic:peat_generator");
  event.hide("cyclic:emerald_sword");
  event.hide("cyclic:emerald_pickaxe");
  event.hide("cyclic:emerald_axe");
  event.hide("cyclic:emerald_hoe");
  event.hide("cyclic:emerald_shovel");
})